p10ks_vcs(1)
============
:compat-mode!:

NAME
----
p10ks_vcs - a shell script

SYNOPSIS
--------

VCS segment that makes use of ZSH's vcs_info builtin autoloadable.

Is async and will run vcs_info in worker process.


FUNCTIONS
---------

 p10ks_vcs
 p10ks_vcs_async
 _p10ks_vcs_async_complete
 p10ks_vcs_async_return
 p10ks_vcs_async_started
 p10ks_vcs_bg
 p10ks_vcs_default_opts
 p10ks_vcs_display_hidden
 +vi-git-aheadbehind
 +vi-git-untracked
 +vi-hg-branchhead
 +vi-vcs-detect-changes
AUTOLOAD vcs_info

ENVIRONMENT VARIABLES
---------------------
[width="80%",cols="4,10"]
|======
|p10ks_battery[color_loading]|bgcolor while async process is running
|p10ks_vcs[backends]|space-separated list of vcs backends; supports 'git', 'svn' and 'hg'
|p10ks_vcs[color_default]|color when repo is clean
|p10ks_vcs[color_dirty]|bgcolor when repo is dirty
|p10ks_vcs[loading_msg]|message while waiting for async process
(set to blank string to hide the segment during async wait)
|======

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 46 line(s). Calls functions:

 Script-Body
 |-- p10ks_vcs
 |-- p10ks_vcs_async
 |   `-- vcs_info
 |-- p10ks_vcs_async_return
 |-- p10ks_vcs_async_started
 `-- p10ks_vcs_bg

Uses feature(s): _autoload_, _zstyle_

p10ks_vcs
~~~~~~~~~

____
 # basic echo of _info_msg_0_
____

Has 2 line(s). Doesn't call other functions.

Called by:

 Script-Body

p10ks_vcs_async
~~~~~~~~~~~~~~~

____
 # }}}
____

Has 27 line(s). Calls functions:

 p10ks_vcs_async
 `-- vcs_info

Uses feature(s): _zstyle_

Called by:

 Script-Body

_p10ks_vcs_async_complete
~~~~~~~~~~~~~~~~~~~~~~~~~

____
 # resets the async status when done with renders
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

p10ks_vcs_async_return
~~~~~~~~~~~~~~~~~~~~~~

Has 6 line(s). Doesn't call other functions.

Called by:

 Script-Body

p10ks_vcs_async_started
~~~~~~~~~~~~~~~~~~~~~~~

Has 3 line(s). Doesn't call other functions.

Called by:

 Script-Body

p10ks_vcs_bg
~~~~~~~~~~~~

Has 5 line(s). Doesn't call other functions.

Called by:

 Script-Body

p10ks_vcs_default_opts
~~~~~~~~~~~~~~~~~~~~~~

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

p10ks_vcs_display_hidden
~~~~~~~~~~~~~~~~~~~~~~~~

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

+vi-git-aheadbehind
~~~~~~~~~~~~~~~~~~~

Has 8 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

+vi-git-untracked
~~~~~~~~~~~~~~~~~

____
 ### GIT hook functions
____

Has 3 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

+vi-hg-branchhead
~~~~~~~~~~~~~~~~~

____
 ### HG hook functions
____

Has 15 line(s). Doesn't call other functions.

Uses feature(s): _read_

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

+vi-vcs-detect-changes
~~~~~~~~~~~~~~~~~~~~~~

____
 ### Generic hook functions
____

Has 5 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

vcs_info
~~~~~~~~

Has 148 line(s). Calls functions:

 vcs_info

Uses feature(s): _autoload_

Called by:

 p10ks_vcs_async

