p10ks_cwd(1)
============
:compat-mode!:

NAME
----
p10ks_cwd - a shell script

SYNOPSIS
--------

Current Working Directory

Renders segment content on the `chpwd` hook.
Has different strategy options for rendering the path.

Right now, the only strategies available are `rtab` and the shell default.

## Options:
- `$1`: FG
- `$2`: BG
- `$3`: Visual Draw Mode
- `$4`: Render Process Mode
- `$5`: DIR Display Strategy
- `$@`: Additional args passed to the chosen strategy


### Common optstrings:

Example dir: `/home/robo/code/configs/zsh`

|===
| optstring        | Example Output |
| `;;;;rtab;`      | `/h/r/c/c/z`   |
| `;;;;rtab;-t;-l` | `~/c/con/zsh`  |
|===

### DIR Display Strategy

|===
| Strategy | Description | Example |
| default | No shortening, just `%~` as evaluated by shell prompt expansion. | `~/code/p10k` |
| `rtab` | Reverse tabbing function, has additional options | `~/c/p10k`, `~/c/p`, `/h/r/c/p`, etc |
|===

### Strategy options:

#### `rtab`:

WARN: The `rtab` strategy uses a single subshell to explore the path.
Although it does spawn a subshell, it is seemingly more performant to explore
the path in a subshell rather than clean up and reset the main thread's chpwd
hooks, variables, etc.

Options can be set with `zstyle` calls, or as arguments `$6...N`

```
-f, --fish      fish-simulation, like -l -s -t
-l, --last      Print the last directory''s full name
-s, --short     Truncate directory names to the first character
-t, --tilde     Substitute ~ for the home directory
-T, --nameddirs Substitute named directories as well
The long options can also be set via zstyle, like
zstyle :prompt:rtab fish yes
```

Note:
> Combined short form (`-sl`) options are *NOT* supported.



FUNCTIONS
---------

 _p10ks_cwd_strat_rtab

ENVIRONMENT VARIABLES
---------------------
[width="80%",cols="4,10"]
|======
|p10ks_cwd|Array for segment runtime use
|p10ks_cwd[add_hyperlink]|If '1', create a hyperlink around the path that is
clickable in most VTE terminals!
|p10ks_cwd[strategy]|The current render strategy for displaying the CWD path
|======

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 5 line(s). No functions are called (may set up e.g. a hook, a Zle widget bound to a key, etc.).

_p10ks_cwd_strat_rtab
~~~~~~~~~~~~~~~~~~~~~

____
 # A modification of the reverse tabbing utility by Daniel Friesel <derf@xxxxxxxxxxxxxxxxxx>
 ## reverse tabbing, useful in the prompt
 ## Copyright (C) 2008 by Daniel Friesel <derf@xxxxxxxxxxxxxxxxxx>
 ## Copyright (C) 2018 by Ben Klein <robobenklein@xxxxxxxxxxxxxxxxxx>
 ## License: WTFPL <http://sam.zoy.org/wtfpl>
 ##
 ## Robobenklein: The original had a CAVEAT:
 ## "directory-names containing two or more consecutive spaces are not supported"
 ## This issue has been fixed.
 ##
 ## Also the script is now a ZSH function instead of an executable shebang file.
____

Has 171 line(s). Doesn't call other functions.

Uses feature(s): _zstyle_

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

