zincs_vcs(1)
============
:compat-mode!:

NAME
----
zincs_vcs - a shell script

SYNOPSIS
--------

VCS segment that makes use of ZSH's vcs_info builtin autoloadable.

Is async and will run vcs_info in worker process.


FUNCTIONS
---------

 +vi-git-aheadbehind
 +vi-git-untracked
 +vi-hg-branchhead
 +vi-svn-detect-changes
 +vi-vcs-detect-changes
 zincs_vcs
 zincs_vcs_async
 _zincs_vcs_async_complete
 zincs_vcs_async_gitstatus
 zincs_vcs_async_gitstatus_start_worker
 zincs_vcs_async_return
 zincs_vcs_async_started
 zincs_vcs_bg
 zincs_vcs_default_opts
 zincs_vcs_display_hidden
AUTOLOAD vcs_info

ENVIRONMENT VARIABLES
---------------------
[width="80%",cols="4,10"]
|======
|zincs_battery[color_loading]|bgcolor while async process is running
|zincs_vcs[backends]|space-separated list of vcs backends; supports 'git', 'svn' and 'hg', otherwise passed to vcs_info

|zincs_vcs[color_default]|color when repo is clean
|zincs_vcs[color_dirty]|bgcolor when repo is dirty
|zincs_vcs[loading_msg]|message while waiting for async process
(set to blank string to hide the segment during async wait)
|zincs_vcs[vcs_icon_status_staged]|icon for vcs staged # ✚ is wide
|zincs_vcs[vcs_icon_status_stashed]|icon for vcs stashed # ⋄
|zincs_vcs[vcs_icon_status_unstaged]|icon for vcs unstaged  # ●
|zincs_vcs[vcs_icon_status_untracked]|icon for vcs untracked # ◌
|======

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 52 line(s). No functions are called (may set up e.g. a hook, a Zle widget bound to a key, etc.).

+vi-git-aheadbehind
~~~~~~~~~~~~~~~~~~~

Has 8 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

+vi-git-untracked
~~~~~~~~~~~~~~~~~

____
 ### GIT hook functions
____

Has 3 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

+vi-hg-branchhead
~~~~~~~~~~~~~~~~~

____
 ### HG hook functions
____

Has 15 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

+vi-svn-detect-changes
~~~~~~~~~~~~~~~~~~~~~~

____
 # SVN hook functions
____

Has 14 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

+vi-vcs-detect-changes
~~~~~~~~~~~~~~~~~~~~~~

____
 ### Generic hook functions
____

Has 5 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

zincs_vcs
~~~~~~~~~

____
 # basic echo of _info_msg_0_
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

zincs_vcs_async
~~~~~~~~~~~~~~~

____
 # }}}
____

Has 10 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_zincs_vcs_async_complete
~~~~~~~~~~~~~~~~~~~~~~~~~

____
 # resets the async status when done with renders
____

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

zincs_vcs_async_gitstatus
~~~~~~~~~~~~~~~~~~~~~~~~~

Has 23 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

zincs_vcs_async_gitstatus_start_worker
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Has 3 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

zincs_vcs_async_return
~~~~~~~~~~~~~~~~~~~~~~

Has 7 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

zincs_vcs_async_started
~~~~~~~~~~~~~~~~~~~~~~~

Has 2 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

zincs_vcs_bg
~~~~~~~~~~~~

Has 5 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

zincs_vcs_default_opts
~~~~~~~~~~~~~~~~~~~~~~

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

zincs_vcs_display_hidden
~~~~~~~~~~~~~~~~~~~~~~~~

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

vcs_info
~~~~~~~~

____
 ##
 ## vcs_info - provide version control information
 ##
 ## Written by Frank Terbeck <ft@bewatermyfriend.org>
 ##
 ## This file and all corresponding files in Functions/VCS_Info/ are
 ## distributed under the same BSD-ish license as zsh itself.
 ##
____

Has 148 line(s). Calls functions:

 

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

