zincs_execution_time(1)
=======================
:compat-mode!:

NAME
----
zincs_execution_time - a shell script

SYNOPSIS
--------

Execution time of last command

## Options:
- `$1`: FG
- `$2`: BG
- `$3`: Display Mode: see latter section.
- `$4`: Only async mode `notify_complete` is supported.
- `$5`: Optional minimum time for `CONDITIONAL` display mode.

### Display Mode

This segment supports the `CONDITIONAL` display mode. (This is the default display mode.)

The condition here is whether or not the execution time of the last command was greater than `zincs_execution_time[threshold]`, if `true` then the segment will be shown.

You can also pass the threshold value as segment option 5, ex:

```shell
zinc_opts=(
zincs_execution_time ';;;;10' # 10 seconds
)
# OR if you've already set zinc_opts:
zinc_opts[zincs_execution_time]=';;;;10'
# then do zinc setup
```

Note:
> `$5` is used at load-time while `zincs_execution_time[threshold]` is used during runtime.

If you don't want the execution time to stick around after creating a newline
(ex. pressing enter without a command)
then you can use the clear_on_redraw segment config variable as shown below.



FUNCTIONS
---------

 zincs_execution_time
 _zincs_execution_time_async_complete
 zincs_execution_time_default_opts
 zincs_execution_time_display_hidden
 _zincs_execution_time_precmd
 _zincs_execution_time_preexec

ENVIRONMENT VARIABLES
---------------------
[width="80%",cols="4,10"]
|======
|zincs_execution_time[clear_on_redraw]|1 or 0 (true/false, default is false) clear the result after the async tasks are done
|zincs_execution_time[threshold]|minimum seconds of runtime to display segment
|======

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 26 line(s). Calls functions:

 Script-Body
 |-- zincs_execution_time
 `-- zincs_execution_time_display_hidden

zincs_execution_time
~~~~~~~~~~~~~~~~~~~~

Has 1 line(s). Doesn't call other functions.

Called by:

 Script-Body

_zincs_execution_time_async_complete
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Has 4 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

zincs_execution_time_default_opts
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

zincs_execution_time_display_hidden
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Has 5 line(s). Doesn't call other functions.

Called by:

 Script-Body

_zincs_execution_time_precmd
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Has 22 line(s). Doesn't call other functions.

Uses feature(s): _read_

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_zincs_execution_time_preexec
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

____
 # synopsis {{{
 # Execution time of last command
 #
 # ## Options:
 # - `$1`: FG
 # - `$2`: BG
 # - `$3`: Display Mode: see latter section.
 # - `$4`: Only async mode `notify_complete` is supported.
 # - `$5`: Optional minimum time for `CONDITIONAL` display mode.
 #
 # ### Display Mode
 #
 # This segment supports the `CONDITIONAL` display mode. (This is the default display mode.)
 #
 # The condition here is whether or not the execution time of the last command was greater than `zincs_execution_time[threshold]`, if `true` then the segment will be shown.
 #
 # You can also pass the threshold value as segment option 5, ex:
 #
 # ```shell
 # zinc_opts=(
 #   zincs_execution_time ';;;;10' # 10 seconds
 # )
 # # OR if you've already set zinc_opts:
 # zinc_opts[zincs_execution_time]=';;;;10'
 # # then do zinc setup
 # ```
 #
 # Note:
 # > `$5` is used at load-time while `zincs_execution_time[threshold]` is used during runtime.
 #
 # If you don't want the execution time to stick around after creating a newline
 # (ex. pressing enter without a command)
 # then you can use the clear_on_redraw segment config variable as shown below.
 #
 # }}}
____

Has 4 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

