zincs_cwd(1)
============
:compat-mode!:

NAME
----
zincs_cwd - a shell script

SYNOPSIS
--------

Current Working Directory

Renders segment content on the `chpwd` hook.
Has different strategy options for rendering the path.

Right now, the only strategies available are `rtab` and the shell default.

## Options:
- `$1`: FG
- `$2`: BG
- `$3`: Visual Draw Mode
- `$4`: Render Process Mode
- `$5`: DIR Display Strategy
- `$@`: Additional args passed to the chosen strategy


### Common optstrings:

Example dir: `/home/robo/code/configs/zsh`

|===
| optstring        | Example Output
| `;;;;rtab;`      | `/h/r/c/c/z`
| `;;;;rtab;-t;-l` | `~/c/con/zsh`
|===

### DIR Display Strategy

|===
| Strategy | Description | Example
| default | No shortening, just `%~` as evaluated by shell prompt expansion. | `~/code/zinc`
| `rtab` | Reverse tabbing function, has additional options | `~/c/zinc`, `~/c/p`, `/h/r/c/p`, etc
|===

### Strategy options:

#### `rtab`:

WARN: The `rtab` strategy uses a single subshell to explore the path.
Although it does spawn a subshell, it is seemingly more performant to explore
the path in a subshell rather than clean up and reset the main thread's chpwd
hooks, variables, etc.

Options can be set with `zstyle` calls, or as arguments `$6...N`

```
-f, --fish      fish-simulation, like -l -s -t
-l, --last      Print the last directory''s full name
-s, --short     Truncate directory names to the first character
-t, --tilde     Substitute ~ for the home directory
-T, --nameddirs Substitute named directories as well
The long options can also be set via zstyle, like
zstyle :prompt:rtab fish yes
```

Note:
____
Combined short form (`-sl`) options are *NOT* supported.
____


FUNCTIONS
---------

 zincs_cwd
 _zincs_cwd_chpwd
 zincs_cwd_default_opts
 _zincs_cwd_strat_rtab

ENVIRONMENT VARIABLES
---------------------
[width="80%",cols="4,10"]
|======
|zincs_cwd|Array for segment runtime use
|zincs_cwd[add_hyperlink]|If '1', create a hyperlink ANSI escape around the path that is
clickable in most VTE terminals!
|zincs_cwd[strategy]|The current render strategy for displaying the CWD path
|======

DETAILS
-------

Script Body
~~~~~~~~~~~

Has 9 line(s). Calls functions:

 Script-Body
 `-- zincs_cwd
     `-- _zincs_cwd_chpwd
         `-- _zincs_cwd_strat_rtab

zincs_cwd
~~~~~~~~~

Has 10 line(s). Calls functions:

 zincs_cwd
 `-- _zincs_cwd_chpwd
     `-- _zincs_cwd_strat_rtab

Called by:

 Script-Body

_zincs_cwd_chpwd
~~~~~~~~~~~~~~~~

____
 # Re-renders the segment output on the chpwd hook.
____

Has 10 line(s). Calls functions:

 _zincs_cwd_chpwd
 `-- _zincs_cwd_strat_rtab

Called by:

 zincs_cwd

zincs_cwd_default_opts
~~~~~~~~~~~~~~~~~~~~~~

Has 1 line(s). Doesn't call other functions.

Not called by script or any function (may be e.g. a hook, a Zle widget, etc.).

_zincs_cwd_strat_rtab
~~~~~~~~~~~~~~~~~~~~~

____
 # A modification of the reverse tabbing utility by Daniel Friesel <derf@xxxxxxxxxxxxxxxxxx>
 ## reverse tabbing, useful in the prompt
 ## Copyright (C) 2008 by Daniel Friesel <derf@xxxxxxxxxxxxxxxxxx>
 ## Copyright (C) 2018 by Ben Klein <robobenklein@xxxxxxxxxxxxxxxxxx>
 ## License: WTFPL <http://sam.zoy.org/wtfpl>
 ##
 ## Robobenklein: The original had a CAVEAT:
 ## "directory-names containing two or more consecutive spaces are not supported"
 ## This issue has been fixed.
 ##
 ## Also the script is now a ZSH function instead of an executable shebang file.
____

Has 93 line(s). Doesn't call other functions.

Uses feature(s): _zstyle_

Called by:

 _zincs_cwd_chpwd

