#!source

if [[ ${PWD%%p10k} != ${PWD} ]]; then
  [[ -d "zsdoc/data" ]] && rm -r zsdoc/data

  zsh ./zsdoc-gen/generate.zsh && {
    zsd \
    --cignore '(\#*vim*|\# AUTOGENERATED*)' \
    -f p10k_functions:segments zsdoc-src/**/*
  } || {
    echo hmmmm
  }
fi
