
local pzsd_segment_sources=${pzsd_segment_sources:-segments}
local pzsd_outputfolder=${pzsd_outputfolder:-zsdoc-src}

set -e

function zsh_cat_file () {
  local -a lines
  lines=( "${(@f)"$(<${1})"}" ) 2>/dev/null
  printf '%b' "\n# AUTOGENERATED - DO NOT EDIT\n"
  print "${(j.\n.)lines}"
  printf '%b' "\n# AUTOGENERATED - DO NOT EDIT\n"
}

function create_doc_scaffold () {
  local outputfile="$1"
  local segment="$2"
  echo > $outputfile
  [[ -s "${pzsd_segment_sources}/zincs_${segment}" ]] || {
    echo "Could not load source ${pzsd_segment_sources}/zincs_${segment}"
  }
  zsh_cat_file "${pzsd_segment_sources}/zincs_${segment}" >> $outputfile
  # printf '%b' "\n# ZINC Autodoc added: \n" >> $outputfile
  zsh_cat_file "${pzsd_segment_sources}/zincs_${segment}_default_opts" >> ${outputfile}
  zsh_cat_file "${pzsd_segment_sources}/zincs_${segment}_display_hidden" >> ${outputfile} || true
  zsh_cat_file "${pzsd_segment_sources}/zincs_${segment}_bg" >> $outputfile || true
  zsh_cat_file "${pzsd_segment_sources}/zincs_${segment}_fg" >> $outputfile || true
  # if async
  zsh_cat_file "${pzsd_segment_sources}/zincs_${segment}_async" >> $outputfile || true
  zsh_cat_file "${pzsd_segment_sources}/zincs_${segment}_async_return" >> $outputfile || true
  zsh_cat_file "${pzsd_segment_sources}/zincs_${segment}_async_started" >> $outputfile || true
}

mkdir -p "${pzsd_outputfolder}/segments"

local -a segments
segments=(
  battery
  cwd
  cwd_writable
  execution_time
  host
  jobs
  retval
  time
  user
  userhost
  vcs
  virtualenv
)

for segment in ${segments}; do
  echo making $segment
  create_doc_scaffold ${pzsd_outputfolder}/zincs_${segment} $segment
done
