#!source

if [[ ${PWD%%zinc} != ${PWD} ]]; then
  [[ -d "zsdoc/data" ]] && rm -r zsdoc/data

  zsh ./zsdoc-gen/generate.zsh && {
    zsd --verbose \
    --cignore '(\#*vim*|\# AUTOGENERATED*)' \
    -f zinc_functions:segments zsdoc-src/**/*
  } || {
    echo hmmmm
  }
fi
